export { useStudentHistory } from './api/adminQueries'
export { useFulfillMakeupCredit, useMakeupCredits } from './api/makeupCredits'
export { AdminAttendancePage } from './components/AdminAttendancePage'
export { MakeupCreditsCard } from './components/MakeupCreditsCard'
export { MarkAttendancePage } from './components/MarkAttendancePage'
export { PendingSavesIndicator } from './components/PendingSavesIndicator'
export { computeTotals, totalsByMonth } from './hooks/attendancePct'
export { attendanceLabel, attendanceTone, pctColorClass } from './hooks/attendanceTone'
export type { AttendanceHistoryRow, AttendanceTotals, MakeupCredit } from './types'
